### ISSUE TITLE
goBack issues

### ISSUE THREAD

**Issue by stereodenis** [react-navigation/react-navigation#2454]
- [x] Change goBack transition #2136 
- [x] goBack() doesn't work #1522
- [x] StackNavigator - custom GoBack route #1731
- [x] How to goBack with some params? #2127
- [x] How to refresh Screen after goback () #1891
- [x] Unable to goBack and setParams #288
- [x] Nested Navigator goback problems #2549
- [x] [goBack]: Go back TO rather than FROM? #1213
- [x] goBack to previous screen instead of Stack #1695
- [x] Failed to get Params on page coming using goBack() #2296
- [x] goBack doesn't trigger TextInput autofocus #1752
- [x] Feature: Pass down props in goBack method #1885
- [x] Issue: header not hidden when calling navigation.goBack() #1834
- [x] goBack doesn't work with following steps from office doc #1699
- [x] goBack or dispatch - do the screens actually pop off? #737
- [x] Don't render twice when goBack and re navigate on same screen #2331
- [x] Navigating back from pre-built nested route #2419
- [x] Go back And the callback function #1692

**Comment by spencercarli** [comment]
Hey thanks for reference list! Will be useful once we have github issues under control and start tackling code issues.

**Comment by guoliang1206** [comment]
goBack(), is a big big big issue of this lib.

**Comment by wuyunqiang** [comment]
goback('home') and nothing to do.
it's bad!

**Comment by acomito** [comment]
I just noticed this as well. Is it new? I don't recall having problems before.

**Comment by rpopovici** [comment]
@stereodenis some of these issues are being discussed here https://github.com/react-community/react-navigation/issues/723 and some potential solutions in these PRs:
idempotent pushes #2334
queued action dispatch #1313
queued transitions in Transitioner #2400

**Comment by rtman** [comment]
would be great if these were fixed, some are quite essential.

**Comment by dragonwong** [comment]
+1

**Comment by kelset** [comment]
Hi @stereodenis - thanks for creating this issue to keep track of the issues related to goBack. We are still working around it code-wise, and I've created a dedicated label for issues in order to not need this list (and you to keep it updated). So I'm going to close this now.

**Comment by phuwn** [comment]
This may solves all of you guys problem: 
https://stackoverflow.com/questions/44223727/react-navigation-goback-and-update-parent-state
