### ISSUE TITLE
React Navigation 2.0 roadmap

### ISSUE THREAD

**Issue by brentvatne** [react-navigation/react-navigation#3685]
### Planned features

- [x] New createNavigator API (https://github.com/react-navigation/react-navigation/pull/3392)
- [x] Real DrawerRouter (https://github.com/react-navigation/react-navigation/pull/3618)
- [x] 'dismiss' helper that calls goBack with the parent key (https://github.com/react-navigation/react-navigation/pull/3669)
- [x] `dangerouslyGetParent` helper (https://github.com/react-navigation/rfcs/issues/27)
- [x] Make stack actions bubble like navigate (https://github.com/react-navigation/react-navigation/pull/3617)
- [x] Less pushy Navigate behavior (https://github.com/react-navigation/rfcs/pull/25)
- [x] Minimize React 16.3 warnings by moving away from lifecycle methods where possible (unable to do this for Transitioner.js, needs more refactoring for this to work)
- [x] Extract tab navigator to separate library that exports `BottomTabNavigation`, `MaterialBottomTabNavigation` and `MaterialTopTabNavigation`. Add deprecated lib for the old behavior. Add examples to NavigationPlayground.
- [x] Shallow navigation options (rfc merged) (https://github.com/react-navigation/rfcs/pull/26)
- [x] New Drawer router and actions
- [x] State persistence (https://github.com/react-navigation/react-navigation/pull/3716)
- [x] New Actions API (https://github.com/react-navigation/react-navigation/pull/3619 and https://github.com/react-navigation/rfcs/pull/18)

### Documentation updates

- [x] Shorthand w/o `screen`
- [x] Limitations section of docs
- [x] Persistence
- [x] Update Fundamentals section
- [x] Update any Snacks
- [x] Explain `key` (what it means, why)
- [x] Navigate vs push
- [x] Describe how `navigationOptions` are resolved and how to set them directly on navigators
- [ ] Update Tab navigation docs
- [ ] Modular action creators
- [ ] Update navigation prop docs

### Unresolved questions

- [x] Should `pop` and `popToTop` actually bubble up?

### Bugs to fix

- [x] Verify that we avoid race conditions around Transitioner navigation completion
- [ ] Update Flow definition

### Bonus

- [x] Make navigation playground look much nicer on android
- [x] Docs for navigator ref at top level (https://github.com/react-navigation/react-navigation.github.io/pull/85)

### Post-2.0 followup

- [ ] Add link to CS50 lecture
- [ ] Add link to React Amsterdam talk
- [ ] Add section to documentation about how to change navigation options on parent navigator from nested route
- [ ] Cache descriptors
- [ ] Compare with projects running 1.x and resolve performance regressions where possible
- [ ] Docs for 'partial overlays' (eg: built-in react-native Modal component)
- [ ] Get react-native-web support working well again (deliverable: an example project that uses it with react-native-web)

### Feedback?

Discussion on this thread is intended for collaborators only. If you're not a collaborator on this project and you think something is missing, please create a feature request or RFC!

https://react-navigation.canny.io/feature-requests
https://github.com/react-navigation/rfcs

### Closes

- https://github.com/react-navigation/react-navigation/issues/3265

**Comment by brentvatne** [comment]
I also posted a rough wishlist for 3.0 here: https://github.com/react-navigation/react-navigation/issues/3686

**Comment by ssssssssssss** [comment]
What's the ETA for 2.0 release? I noticed some animation related works are not included in either 2.0 or 3.0, such as "Customizable per-screen transitions", "Shared Element Transition", "Put <header/> in render". And the performance audit should have higher priority IMHO. Thanks for working on this.

**Comment by brentvatne** [comment]
@ssssssssssss - join in the rfcs for those. eta is when we check off all of those boxes. if you think performance audit is higher priority then you're welcome to go ahead and do it, it doesn't require any special skills, just digging around and accounting for re-renders.

**Comment by brentvatne** [comment]
via @skabbes re: react-native-web

> These files aren't complete, but they are plucked out from a successful (closed-source) usage of react-navigation 1.5.8 with react-native-web@latest.
>
> While a blog post would be nice when I have a minute free, I'd like to give this to someone who wants to give it a try before I do.

https://gist.github.com/skabbes/0bfa0a969aac8ec13f716dda1ad2ab43

**Comment by brentvatne** [comment]
done

**Comment by brentvatne** [comment]
https://reactnavigation.org/blog/2018/05/07/react-navigation-2.0.html
