### ISSUE TITLE
React Navigation 3.0 Roadmap

### ISSUE THREAD

**Issue by brentvatne** [react-navigation/react-navigation#4434]
- [ ] breaking change: manually wrap your app in navigation container (@ericvicenti)
- [ ] split out drawer, react-native-gesture-handler on drawer & better drawer performance and behavior in general (eg: fix weird drawer behavior where inactive screens are unmounted by default) (@brentvatne)
- [ ] status bar config in navigationOptions (@ericvicenti)
- [ ] screen orientation in navigationOptions (no common primitive in all react-native projects)
- [ ] simpler transitioner implementation (@ericvicenti) (keep in mind that we may want per-screen transitions)
- [ ] better story around modals (full screen and partial overlays)
- [ ] better safe area view (status bar translucent/opaque/varying height, safe areas, maybe keyboard?)
- [ ] make safe area view navigation-aware (translucent header)
- [ ] export a scrollview component that scrolls to top automatically when tapping tab icon and already at first screen in stack for that tab. it should also handle insets with translucent headers and tabbars. (@brentvatne) 
- [ ] header layout sanity https://github.com/react-navigation/react-navigation/issues/4092 (@brentvatne)
- [ ] more intuitive reset (lots of issues, eg: https://github.com/react-navigation/react-navigation/issues/691)
- [ ] integration tests that we can use for focus events (@ericvicenti)
- [ ] improve web support: experimental subrepo (@ericvicenti)
- [ ] resourcesavingcontainer on stack on android and drawer for both ios and android ([feature request](https://react-navigation.canny.io/feature-requests/p/improve-memory-usage-with-resource-saving-container-integration-to-cardstack-tab))
- [ ] audit performance: be able to explain why we do each render on every re-render of a screen or header 
- [ ] some way to let people animate between screens in switchnavigator
- [ ] support translucent bottom tab bar
- [ ] hiding tabs from tabbar ([feature request](https://react-navigation.canny.io/feature-requests/p/hiding-tab-from-the-tabbar)) - whether we implement this or not, understand what people want to do and explain how to achieve behavior in docs

**Comment by brentvatne** [comment]
if you have feature requests, post to https://react-navigation.canny.io/feature-requests
for proposals, post to https://github.com/react-navigation/rfcs
