### ISSUE TITLE
React Navigation 4.0 Roadmap

### ISSUE THREAD

**Issue by brentvatne** [react-navigation/react-navigation#5328]
This will be a small release. The main purpose of it is to add react-native-reanimated and switch stack and drawer over to it. Adding reanimated to stack will finally allow us to resolve [this](https://github.com/react-navigation/react-navigation-stack/issues/63), but it will be potentially a difficult change for people with heavily customized transitions.

- [ ] Add peer dependency on react-native-reanimated
- [ ] Make stack navigator use reanimated
- [x] Make drawer use reanimated
- [ ] Enable react-native-screens by default (but let people opt-out still)
- [x] Additional backBehavior implementations for SwitchRouter (https://github.com/react-navigation/rfcs/pull/2)
- [ ] Status bar config in navigationOptions

**Comment by eriveltonelias** [comment]
👏👏👏

**Comment by satya164** [comment]
25b97b235bc7bf8f1b63bb0c4e1601ccf623c046
