### ISSUE TITLE
Basic web support

### ISSUE THREAD

**Issue by EvanBacon** [react-navigation/react-navigation#5674]
React Navigation + Expo should work (not break) on the web. Because of the move to screens and gesture handler, web support was temporarily unsupported. With Expo for web, React Navigation will be the universal navigation library. 

* Web navigation by default should be visually more similar to android than to iOS
* Navigation on web should opt to use Switch navigation whenever possible

# TODO

- [x] [react-navigation-core](https://github.com/react-navigation/react-navigation-core) related react-navigation/react-navigation-core#45
- [x] [react-navigation-stack](https://github.com/react-navigation/react-navigation-stack) related react-navigation/react-navigation-stack#93
- [ ] [react-navigation-drawer](https://github.com/react-navigation/react-navigation-drawer)
- [x] [react-navigation-tabs](https://github.com/react-navigation/react-navigation-tabs)
- [x] [react-navigation-web](https://github.com/react-navigation/react-navigation-web)
- [ ] [react-navigation-native](https://github.com/react-navigation/react-navigation-native) (?)
- [ ] [react-navigation-material-bottom-tabs](https://github.com/react-navigation/react-navigation-material-bottom-tabs)

## Portals

- [ ] React navigation stack should use portals to float the header element at the body level: https://github.com/react-navigation/stack/pull/116
- [ ] Tab navigator should probably do the same.

# Related

#4048
#4223
#4223
#1660

**Comment by eriveltonelias** [comment]
hey @EvanBacon! 

thanks for pointing this out, 

I'll leave just an note about the `example-web` repro, is just an example of usage of [react-navigation-web](https://github.com/react-navigation/react-navigation-web) which uses `ReactJs`

**Comment by fbartho** [comment]
>Web navigation by default should be visually more similar to android than to iOS

What’s the rationale behind this point?

**Comment by brentvatne** [comment]
@fbartho - find be a website that looks like ios and isn't trash ;)

**Comment by slorber** [comment]
hey, just wondering, how do we support accessibility with react-navigation-web?

I mean, on the web we don't do `navigation.navigate({routeName: "Screen"})` but we rather present a link to the user. And hovering that link should enable us to see the link target. Pressing with mouse wheel should open in new tab etc. Can we keep all these behaviors without changing a little bit the primitives of react-navigation?

**Comment by AndrewMorsillo** [comment]
I added a related issue to the react-navigation site about the documentation for web use

https://github.com/react-navigation/react-navigation.github.io/issues/531
