### ISSUE TITLE
Roadmap for v6

### ISSUE THREAD

**Issue by satya164** [react-navigation/react-navigation#8981]
This is a list of potential changes we want to have for v6.

WIP branch: https://github.com/react-navigation/react-navigation/tree/6.x

**General**

- [x] Overwrite params instead of merging for all actions except `setParams`. This has been a source of confusion
- [x] API to provide default screen options (for custom navigators)
- [x] Warn on duplicate screen names across navigators
- [x] Don't expose `state` property on `route` prop (probably expose with a non-enumerable symbol property for internal APIs)
- [x] Drop legacy linking config, validate linking config against navigation state against state changes in development mode and warn about misconfiguration
- [ ] ~Perform validation of the linking config to identify errors such conflicting screens for patterns on initial render rather than on each invocation of `getStateFromPath`~
- [ ] ~Accept a function instead of a component in `createNavigatorFactory` (for custom navigators). This would let us automatically wrap them in `React.forwardRef` and allow exposing the `ref` on individual navigators as well~
- [x] Drop support for older versions of `react-native-safe-area-context` and `reacct-native-screens` to cleanup the code
- [x] Use `@react-native-masked-view/masked-view` instead of `@react-native-community/masked-view` (or perhaps drop it altogether? need to check if metro supports optional require now)
- [x] Remove the compat package from repo
- [x] Stop exporting `useLinking` hook
- [x] Drop support for older versions of TypeScript and add names inside tuples (e.g. for `navigate`)
- [ ] ~Warn when a navigation method was called inside render~
- [x] Drop usage of dimensions and use window metrics from safe area context
- [x] Migrate components to `Pressable`
- [ ] ~Use system colors in default theme~

**Stack**

- [x] Drop `headerMode="none"`. There's already `headerShown` option which is more granular, and it's better not to have 2 ways of doing the same thing
- [x] Add deprecation warning for `headerMode="none"` and convert it to `headerShown: false` under the hood
- [x] Use the modal presentation animation on iOS when `mode` is set to `modal`, and maybe a slide up animation (similar to twitter app) for Android
- [x] Streamline header's props, pass `route`, `descriptor` and `navigation` as direct props, make `scene` contain the animation. The `previous` prop can contain `scene`, and `descriptor` properties
- [ ] Investigate: support pre-loading screens, this means that if `routes` array contains more routes then what's in `index`, they wouldn't trimmed automatically, and those extra routes would be considered as preloaded by rendering them offscreen.

**Drawer**

- [x] Drop `drawerOpen` and `drawerClose` events. It's already possible to do that with `useIsDrawerOpen` or manually with `state` listeners and `getIsDrawerOpenFromState`
- [x] Default to `drawerType="slide"` on iOS as it seems more common in iOS apps
- [x] Use an enum to represent drawer state, which will allow us to implement states like collapsed in future
- [ ] Standardized API for drawer animations (maybe before the major)
- [x] Move `drawerContentOptions` into `options` to reduce confusion and provide more flexibility
- [x] For `lazy` prop, let it be more specific regarding which screens should be lazily loaded
- [x] Keep supporting `drawerContentOptions` with deprecation warnings

**Bottom Tabs**

- [x] Remove `tabBarVisible` option, changing it mid-animation causes jank due to layout shifting. this can still be achieved using `style` prop for people who need it (we need to move `tabBarStyle` to `options`)
- [x] Move `tabBarOptions` into `options` to reduce confusion and provide more flexibility
- [x] For `lazy` prop, let it be more specific regarding which screens should be lazily loaded
- [x] Keep supporting `tabBarOptions` with deprecation warnings
- [x] Change `backBehavior` to `firstRoute`

**Material Top Tabs**

- [x] Move `tabBarOptions` into `options` to reduce confusion and provide more flexibility
- [x] For `lazy` prop, let it be more specific regarding which screens should be lazily loaded
- [x] Keep supporting `tabBarOptions` with deprecation warnings

**Component library**

- [x] New component library containing components like `TouchableItem`, `Header` etc. that's shared by multiple navigators

**Comment by signorettif** [comment]
Support for reanimated 2?

**Comment by kdo1234** [comment]
If the compat package is removed from the repo what should we use instead of `withNavigation` for class components? Thank you

**Comment by satya164** [comment]
@kdo1234 the package will be removed from master branch but will stay on 5.x branch as well as npm, and will continue to work with 6.x.

**Comment by vujevits** [comment]
_Don't expose state property on route prop (probably expose with a non-enumerable symbol property for internal APIs)_
it's a workaround for me at the moment to check in some cases the current path, if it's not exposed, is there another way to do that?

**Comment by satya164** [comment]
@vujevits what do you mean by current path?

**Comment by mschipperheyn** [comment]
I would suggest putting react-native-reanimated v2 on the v6 roadmap. Animation performance is a weakness and should be eliminated by reanimated, which is close to release it seems.

**Comment by ltcaosj** [comment]
I am with you @mschipperheyn. react-native-reanimated v2 is awesome.

**Comment by vujevits** [comment]
> @vujevits what do you mean by current path?

How to obtain the routeName which was assigned to the current screen.
This is the code what I use for it at the moment:
```JavaScript
const route = useRoute();
const routes = route.state.routes[0].state.routes;
currentRouteName = routes[routes.length - 1].name;

**Comment by satya164** [comment]
> @mschipperheyn I would suggest putting react-native-reanimated v2 on the v6 roadmap

We'll eventually get to it, but right now Reanimated 2 isn't suitable for being default:

- It requires Turbo Modules which aren't default in React Native yet
- It needs Hermes to be used which not everyone can upgrade to since some libraries don't work with it and it's missing some things
- We also need to think about improving the DX first since there are other setups you need to do to get started with Reanimated 2, such as configuring the Babel plugin

We're trying to get [native stack](https://reactnavigation.org/docs/native-stack-navigator/) to a state where it can be recommended by default, which will help if you have performance issues.

> @vujevits How to obtain the routeName which was assigned to the current screen

The main reason it's being removed is because what you're doing isn't safe and there are many cases where you won't get the correct value, even if it might seem to work fine in your specific case. There's no way to workaround that since accessing child component's state directly isn't something React supports.

I don't know what your use case is, but if you just need to current route name for some side effect, then there are `getRootState` and `getCurrentRoute` method on the container ref. Otherwise you can expose a callback via context and call that callback with the focused screen name from child.

**Comment by vujevits** [comment]
thanks @satya164 I'll try the mentioned methods. Not a typical usecase, I'm using react-native-web, and on that platform have to provide a different experience. It is needed for one of the workarounds.

**Comment by satya164** [comment]
@vujevits To replicate your exact behaviour, you can do:

```js
function useCurrentRouteName() {
  const route = useRoute();
  const currentRouteName = useNavigationState((state) => {
    const routes = state.routes.find((r) => r.key === route.key).state.routes[0]
      .state.routes;
    return routes[routes.length - 1].name;
  });
  return currentRouteName;
}
```

Or the more reliable method would be to listen for the URL change:

```js
function useCurrentURL() {
  const [url, setURL] = React.useState(window.location.href);

  React.useEffect(() => {
    const onURLChange = () => setURL(window.location.href);
    window.addEventListener('popstate', onURLChange);
    return () => window.removeEventListener('popstate', onURLChange);
  });
}
```

**Comment by fedyk** [comment]
> @vujevits To replicate your exact behavior, you can do (though it's still problematic):

Thanks for your answer.

I have one more question. How about cases when you need the current route (not only name) outside React? For instance, the [case](https://reactnavigation.org/docs/screen-options-resolution/#setting-parent-screen-options-based-on-child-navigators-state) from doc when you have a method `getHeaderTitle` and result depends on route params/options(not only name):

```js
function getHeaderTitle(route) {
  const focusedRoute = /* ? */

  switch (focusedRoute.routeName) {
    case 'Feed':
      return `${focusedRoute.params.dummyCounter} - News Feed`;
   // ...
  }
}

```

**Comment by satya164** [comment]
@fedyk you'll either need to lift the param up to the route that needs it (similar to lifting state up), or have a callback in the child component which updates the the counter in parent.

**Comment by ksitko** [comment]
@satya164 
> We're trying to get [native stack](https://reactnavigation.org/docs/native-stack-navigator/) to a state where it can be recommended by default, which will help if you have performance issues.

Glad to hear that native stack is getting some love, but unfortunately it isn't the be all and all solution for all users. As of writing [react-navigation-shared-element](https://github.com/IjzerenHein/react-navigation-shared-element/issues/14) does not support native stack. Pulling more performance out of non native screen transitions via Reanimated V2 would be very desirable.

**Comment by EyMaddis** [comment]
I would like to note that overriding router behaviour is currently very tedious. 
Let's say I want to simply disallow navigations conditionally.
The docs state an [example](https://reactnavigation.org/docs/custom-routers#blocking-navigation-actions) in combination with [custom navigators](https://reactnavigation.org/docs/custom-navigators#extending-navigators).
The bottom bar example is trivial because stacks contain a lot more code than just `useNavigationBuilder` in combination with `<{NAVIGATORNAME}View ... />`.

That is a lot of code I need to copy pase from the original package in order to include a simple `if`. 

I think react-navigation could easily provide a guard feature/route level callbacks to make something like this a very simple one liner. 
The same goes for conditional redirects.

Generally, the library assumes that I should either handle all my before using `navigate()` or I need to get the big guns like a custom navigator.
I think some settings should be possible at route level that automatically applies to all `navigate/push/replace` and even deep linking without all the hassle.

**Comment by nandorojo** [comment]
> We're trying to get native stack to a state where it can be recommended by default

@satya164 I think this makes sense. I've had much better performance with native stack. 

As noted above, one thing that would elevate the native stack a lot is shared element transitions. 

While react-navigation-shared-element exists, it isn't very actively maintained for adding features (such as native stack support.) I think it could make a big difference if this feature came directly from react-navigation or react-native-screens. It's tough to pick between the great UX of shared elements and the smooth performance of the native stack.

**Comment by ChronSyn** [comment]
As an addition to V6 drawer roadmap, would it be possible to get some `onDrawerOpen` and `onDrawerClose` events added to `createDrawerNavigator().Navigator`?

Alternatively, allow developers to provide a ref to the `createDrawerNavigator().Navigator` as well as optionally providing a ref to the `useIsDrawerOpen` hook (if no ref is provided, assume the existing behaviour)?

Another alternative, though perhaps not fixing the core issue, would be to add the option to pass a ref to the `useNavigation` hook, as well as allowing developers to provide a ref to the `createDrawerNavigator().Navigator`.

Maybe implementing all 3 would be a good option. I personally prefer the former, as that implements an event-driven process for managing drawer state (and allowing users to trigger state-driven effects without needing to track a ref), but either would be fantastic additions.

I've come across numerous use-cases where apps will have multiple drawers, and have found that the `useIsDrawerOpen` hook is unable to differentiate which drawer I'm referencing.

As an example, one of our products has a right-aligned drawer for navigating through the app, and a left-aligned drawer used for displaying a detailed view (with the main body being a stack navigator which displays a list of items). When the left-aligned or right-aligned drawer is open, the `useIsDrawerOpen` hook reports true. However, if we then close one of the drawers, the hook reports false, but it is not possible to identify which drawer it references. This means that when we call a method to open the drawer (e.g.`useNavigation().openDrawer()`), the library doesn't know which drawer is should open.

We have to keep track of the state of each drawer to handle other elements of our UI and app experience, and right now, this feels like an impossible hurdle to overcome.

**Comment by satya164** [comment]
@ChronSyn you can use `getParent()` (6.x) or `dangerouslyGetParent()` (5.x) to get the navigation prop of the parent. You can add a listener on the `navigation` object to get state updates:

```js
import { getDrawerStatusFromState } from '@react-navigation/drawer'; // `getIsDrawerOpenFromState` in 5.x

// ...

navigation.getParent().addListener('state', e => {
  const drawerStatus = getDrawerStatusFromState(e.data);
});
```

PR welcome to add a section in docs about using multiple drawers together.

**Comment by Razorholt** [comment]
So, regarding params, navigating from screen1 to screen2, Will that work?

```
function screen1({navigation}) {
     navigation.navigate(screen2, { postTitle: 'An okay post' })
}

function screen2({route}) {
     const mypostTitle = route.postTitle;
}
```

**Comment by AxelHgt** [comment]
react-native-reanimated v2 is out ! 
It could be interesting to use it in the V6

**Comment by liamjones** [comment]
>It could be interesting to use it in the V6

Yep, but keep in mind that react-native-reanimated v2 requires Hermes to be used and that isn't necessarily possible for everyone.

**Comment by ksitko** [comment]
> that isn't necessarily possible for everyone.

While that may be true, Hermes is without a doubt the direction RN is going. As a major release it's quite reasonable to expect breaking changes.

**Comment by liamjones** [comment]
@ksitko Oh, I agree - I was just making sure that people here were aware that, for some, it _is_ a breaking change right now. :)

The main one that comes to mind is Realm, although I know Hermes support is at the top of their backlog to tackle (https://github.com/realm/realm-js/issues/2455).

**Comment by satya164** [comment]
https://github.com/software-mansion/react-native-reanimated/pull/1842

**Comment by RohovDmytro** [comment]
Would the decision about reanimated v1 would be reconsidered due to software-mansion/react-native-reanimated#1842 ?

**Comment by ksitko** [comment]
Not only is JSC for Android now supported in the latest Reanimated release, 2.1.0, but it appears to have backwards compatibility: https://github.com/software-mansion/react-native-reanimated/pull/1845

**Comment by satya164** [comment]
> Would the decision about reanimated v1 would be reconsidered due to software-mansion/react-native-reanimated#1842 ?

I'm not sure what you are asking. Why does it matter to you as a consumer which APIs we use internally? Reanimated 2 is mostly backward compatible and React Navigation already works fine with it.

Even if JSC is now supported in Reanimated 2, it uses turbo modules which means you can't debug your app in Chrome debugger. You still need to use Hermes to be able to debug it with Flipper, also Expo doesn't support Flipper so using Reanimated 2 means Expo users won't even be able to debug their app.

There are no disadvantages in supporting Reanimated 1, and many shortcomings if we drop support for Reanimated 1. I don't see any reason to do that as it'll make it impossible to use for a lot of people.

**Comment by theMasix** [comment]
I just had a question about `react-navigation@5` compatibility with `react-native-reanimated@2`, and I found that it's not compatible right now. Can someone add this note (Compatibility issue with `react-native-reanimated@2`) to the doc?

**Comment by theMasix** [comment]
I'm now confused! Is `react-navigation@5` compatible with `react-native-reanimated@2` or not? @satya164

**Comment by raajnadar** [comment]
React navigation v5 will work with some extra configuration steps. If you have the latest version of react navigation v5 you will get a warning in the console.

**Comment by theMasix** [comment]
> React navigation v5 will work with some extra configuration steps. If you have the latest version of react navigation v5 you will get a warning in the console.

Could you please explain these extra config steps?
@raajnadar

**Comment by raajnadar** [comment]
https://docs.swmansion.com/react-native-reanimated/docs/installation/

**Comment by dlenskyi** [comment]
@satya164
Can you pls explain how to get active route name for nested navigators without using state?
#9113 in this issue @delanebob explained situation, I have exactly the same situation, and `getFocusedRouteNameFromRoute` can give us active route name only of top layer of navigator
I will appreciate if you tell me how to do it without using route state

**Comment by chj-damon** [comment]
> > We're trying to get native stack to a state where it can be recommended by default
> 
> @satya164 I think this makes sense. I've had much better performance with native stack.
> 
> As noted above, one thing that would elevate the native stack a lot is shared element transitions.
> 
> While react-navigation-shared-element exists, it isn't very actively maintained for adding features (such as native stack support.) I think it could make a big difference if this feature came directly from react-navigation or react-native-screens. It's tough to pick between the great UX of shared elements and the smooth performance of the native stack.

This would be the biggest feature I want to have in v6!  especially `react-native-shared-element` and `react-navigation-shared-element` is not actively maintained

**Comment by ArekChr** [comment]
How to achieve tabBarVisibility from styles? The problem is height because it is outside from useTabBarHeight hook, tabBarVisible needs rework, visibility wasn't possible in v 5.x with BlurView background configuration - animation was broken

**Comment by jsamr** [comment]
Are you considering extracting the react-native-reanimated v2 drawer component to a standalone package? That would be awesome!

**Comment by ArekChr** [comment]
Please add missing hook useHeaderHeight

**Comment by pouyarezvani** [comment]
@satya164 @ArekChr 
How do we achieve the `tabBarVisible` via `style`?
or how do we achieve it at all? Can anyone possibly link a working example/solution? 
in v5 I used to hide it programmatically on certain screens. But sadly after upgrading it doesn't work anymore.

**Comment by ArekChr** [comment]
> @satya164 @ArekChr
> How do we achieve the `tabBarVisible` via `style`?
> or how do we achieve it at all? Can anyone possibly link a working example/solution?
> in v5 I used to hide it programmatically on certain screens. But sadly after upgrading it doesn't work anymore.

    if (isVisible) Animated.timing(visibilityAnimation, { toValue: 0, duration: 150, useNativeDriver: true }).start();
    else Animated.timing(visibilityAnimation, { toValue: 1, duration: 150, useNativeDriver: true }).start();

    return {
        tabBarStyle:  {
              position: 'absolute',
              transform: [
                  {
                      translateY: visibilityAnimation.interpolate({
                          inputRange: [0, 1],
                          outputRange: [0, BOTTOM_TAB_HEIGHT],
                      }),
                  },
              ],
          }
    };

**Comment by SaeedZhiany** [comment]
> Move drawerContentOptions into options to reduce confusion and provide more flexibility

@satya164 

I need to pass some extra props to my custom drawer sidebar component (like some callback handler and etc). in v5 I was passing them using `drawerContentOptions` like below:

```tsx
function renderSidebar(props: DrawerContentOptions<SidebarProps>): React.ReactNode {
  return (<Sidebar key={'sidebar'} {...props}/>);
}
.
.
.

<Drawer.Navigator
  drawerContent={renderSidebar}
  drawerContentProps={{
    theCallbackProp: () => {/* some logic */}
    // other props
  }}
>
  <Drawer.Screen/>
</Drawer.Navigator>
```


I just figure out that the `DrawerContentProps` type has changed and it no longer receives the Generic type like before

```tsx
type DrawerContentProps<T> = T & {/* navigation related props */} -> interface DrawerContentProps { /* navigation props */ }
```


I didn't see any documentation about this breaking change on the [upgrading-from-5.x](https://reactnavigation.org/docs/upgrading-from-5.x) page.


however, how can I achieve the same behavior in v6?

Thanks

**Comment by nandorojo** [comment]
> > We're trying to get native stack to a state where it can be recommended by default
> 
> @satya164 I think this makes sense. I've had much better performance with native stack.
> 
> As noted above, one thing that would elevate the native stack a lot is shared element transitions.
> 
> While react-navigation-shared-element exists, it isn't very actively maintained for adding features (such as native stack support.) I think it could make a big difference if this feature came directly from react-navigation or react-native-screens. It's tough to pick between the great UX of shared elements and the smooth performance of the native stack.

Shared transitions in `native-stack` is becoming a reality.

@IjzerenHein is collecting donations to implement the feature [here](https://github.com/IjzerenHein/react-navigation-shared-element/issues/14#issuecomment-910134144). I just sent $100.

Please consider sponsoring the feature there to help make this happen!

**Comment by sudokzt** [comment]
> the package will be removed from main branch but will stay on 5.x branch as well as npm, and will continue to work with 6.x.

I migrated react-navigation version 4 to 5 before. In this time, I used `@react-navigation/compat`. It's working well.
Now, I wanted to migrate 5 to 6 with `@react-navigation/compat`. But occurs type error in bellow code. `createCompatNavigatorFactory(createStackNavigator)`. Unfortunately this looks like the correct error.

Do you have any plans to fix this error? 

The versions
```
  "@react-navigation/compat": "5.3.20",
  "@react-navigation/native": "6.0.2",
  "@react-navigation/stack": "6.0.7",
```

**Comment by nomi9995** [comment]
@ArekChr @pouyarezvani  you can use `useAnimatedTabbarVisible` hook for getting v5 bottom tabbar animated hide/show. i have added this hook in `@react-navigation/elements`. after the merge #9910 PR 
you can use `import {useAnimatedTabbarVisible} from @react-navigation/elements`
# Hook
```
import { useBottomTabBarHeight } from '@react-navigation/bottom-tabs';
import type { NavigationProp } from '@react-navigation/native';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { Animated, Platform, StyleSheet } from 'react-native';
import { EdgeInsets, useSafeAreaInsets } from 'react-native-safe-area-context';
const useNativeDriver = Platform.OS !== 'web';

const useAnimatedTabbarVisible = (
  navigation: NavigationProp<ReactNavigation.RootParamList>,
  isParentNavigatorFunction: boolean = false,
  isVisible: boolean = true
) => {
  const tabbarheight = useBottomTabBarHeight();
  const insets = useSafeAreaInsets();
  const [isTabBarHidden, setIsTabBarHidden] = useState<boolean>(isVisible);
  const getPaddingBottom = (insets: EdgeInsets) =>
    Math.max(insets.bottom - Platform.select({ ios: 4, default: 0 }), 0);
  const paddingBottom = getPaddingBottom(insets);
  const [visible] = useState(() => new Animated.Value(isVisible ? 1 : 0));
  const tabBarStyle = useMemo(
    () => ({
      position: isTabBarHidden ? 'absolute' : (null as any),
      height: tabbarheight,
      paddingBottom,
      paddingHorizontal: Math.max(insets.left, insets.right),
      transform: [
        {
          translateY: visible.interpolate({
            inputRange: [0, 1],
            outputRange: [
              tabbarheight + paddingBottom + StyleSheet.hairlineWidth,
              0,
            ],
          }),
        },
      ],
    }),
    [isTabBarHidden]
  );
  const setTabbarVisible = useCallback((tabBarVisible) => {
    if (tabBarVisible) {
      const animation = Animated.timing;

      animation(visible, {
        toValue: 1,
        useNativeDriver,
        duration: 250,
      }).start(({ finished }) => {
        if (finished) {
          setIsTabBarHidden(false);
        }
      });
    } else {
      setIsTabBarHidden(true);

      const animation = Animated.timing;

      animation(visible, {
        toValue: 0,
        useNativeDriver,
        duration: 200,
      }).start();
    }
  }, []);

  useEffect(() => {
    isParentNavigatorFunction && setIsTabBarHidden(false);
  }, [isParentNavigatorFunction]);

  useEffect(() => {
    navigation?.setOptions({
      tabBarStyle,
    });
  }, [navigation, isTabBarHidden]);

  return setTabbarVisible;
};

export default useAnimatedTabbarVisible;
```
# Usage
```
const navigation = useNavigation();
const setTabbarVisible = useAnimatedTabbarVisible(navigation);

// for hide
setTabbarVisible(false);

// for show
setTabbarVisible(true);
```

**Comment by pouyarezvani** [comment]
@nomi9995 We are using V6 At the moment. Is your example using v5 or v6?

Thanks

**Comment by nomi9995** [comment]
@pouyarezvani this example is for both v6 and v5. i tested it with v6

**Comment by pouyarezvani** [comment]
@nomi9995 This is very cool. 
Question! Is it possible to refactor this hook to use reanimated v2 API instead of `Animated` from `react-native` ? Simply for better performance.

**Comment by nomi9995** [comment]
@pouyarezvani yes possible but we don't need to refactor with Reanimated 2 because we are using `useNativeDriver`. in this case, performance will be the same in both

**Comment by FrancoisDeBellescize** [comment]
> If the compat package is removed from the repo what should we use instead of `withNavigation` for class components? Thank you

You have access to `import { useNavigation } from '@react-navigation/native';` :

Here is the example : https://reactnavigation.org/docs/use-navigation/
